---
- name: Install base packages
  hosts: west
  gather_facts: no
  tasks:
  - name: Install epel
    package:
      name: epel-release
      state: latest
  - name: Install additional packages
    package: name={{ item }} state=latest
    with_items:
    - npm
    - time

- name: Install npm packages
  hosts: west
  gather_facts: no
  tasks:
  - name: Install npm packages
    npm: name={{ item }} path=/root
    with_items:
    - express
    - socket.io

- name:  Setup wget-api service
  hosts: west
  gather_facts: no
  tasks:
  - name: Put service file in place
    copy:
      src: wget-api.service
      dest: /etc/systemd/system/wget-api.service
  - name: Put wget_server.js in place
    copy:
      src: wget_server.js
      dest: /root/wget_server.js
  - name: Put wget.js in place
    copy:
      src: wget.js
      dest: /root/wget.js
  - name: Start and enable wget-api service
    service:
      name: wget-api
      state: started
      enabled: yes

- name:  Setup window-scaling-api service
  hosts: west
  gather_facts: no
  tasks:
  - name: Put service file in place
    copy:
      src: window-scaling-api.service
      dest: /etc/systemd/system/window-scaling-api.service
  - name: Put window_scaling_server.js in place
    copy:
      src: window_scaling_server.js
      dest: /root/window_scaling_server.js
  - name: Put window_scaling.js in place
    copy:
      src: window_scaling.js
      dest: /root/window_scaling.js
  - name: Start and enable window-scaling-api service
    service:
      name: window-scaling-api
      state: started
      enabled: yes

- name: Setup route script for test interface
  hosts: west
  gather_facts: no
  tasks:
  - name: Setup route file
    copy:
      src: route-test
      dest: /etc/sysconfig/network-scripts/route-test
