---
- name: Install base packages
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Install epel
    package:
      name: epel-release
      state: latest
  - name: Install additional packages
    package: name={{ item }} state=latest
    with_items:
    - npm
    - time
    - nginx

- name: Install npm packages
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Install npm packages
    npm: name={{ item }} path=/root
    with_items:
    - express
    - socket.io
    - node-fetch

- name: Install netdata
  hosts: client-router
  gather_facts: no
  tasks:
  - name: download script
    get_url:
      url: https://my-netdata.io/kickstart.sh
      dest: /root/kickstart.sh
  - name: run script
    shell: bash /root/kickstart.sh all --dont-wait

- name:  Setup ifacectl service
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Put service file in place
    copy:
      src: ifacectl-api.service
      dest: /etc/systemd/system/ifacectl-api.service
  - name: Put ifacectl_server.js in place
    template:
      src: ifacectl_server.js.j2
      dest: /root/ifacectl_server.js
  - name: Put ifacectl.js in place
    copy:
      src: ifacectl.js
      dest: /root/ifacectl.js
  - name: Start and enable ifacectl service
    service:
      name: ifacectl-api
      state: started
      enabled: yes

- name: Setup base qdiscs
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Create rc.local file
    template:
      src: rc.local.j2
      dest: /etc/rc.d/rc.local
      mode: '0755'
  - name: Start and enable rc-local service
    service:
      name: rc-local
      state: started
      enabled: yes

- name:  t128configurator service
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Put service file in place
    copy:
      src: t128configurator-api.service
      dest: /etc/systemd/system/t128configurator-api.service
  - name: Put t128Configurator.js in place
    template:
      src: t128Configurator.js.j2
      dest: /root/t128Configurator.js
  - name: Start and enable t128Configurator service
    service:
      name: t128configurator-api
      state: started
      enabled: yes

- name:  Setup wget-api service
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Put service file in place
    copy:
      src: wget-api.service
      dest: /etc/systemd/system/wget-api.service
  - name: Put wget_server.js in place
    copy:
      src: wget_server.js
      dest: /root/wget_server.js
  - name: Put wget.js in place
    copy:
      src: wget.js
      dest: /root/wget.js
  - name: Start and enable wget-api service
    service:
      name: wget-api
      state: started
      enabled: yes

- name:  Setup window-scaling-api service
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Put service file in place
    copy:
      src: window-scaling-api.service
      dest: /etc/systemd/system/window-scaling-api.service
  - name: Put window_scaling_server.js in place
    copy:
      src: window_scaling_server.js
      dest: /root/window_scaling_server.js
  - name: Put window_scaling.js in place
    copy:
      src: window_scaling.js
      dest: /root/window_scaling.js
  - name: Start and enable window-scaling-api service
    service:
      name: window-scaling-api
      state: started
      enabled: yes

- name: Setup route script for test interface
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Setup route file
    copy:
      src: route-test
      dest: /etc/sysconfig/network-scripts/route-test

- name: Setup nginx
  hosts: client-router
  gather_facts: no
  tasks:
  - name: Setup nginx config
    copy:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Setup vsat.css
    copy:
      src: vsat.css
      dest: /usr/share/nginx/html/vsat.css
  - name: Setup switch.css
    copy:
      src: switch.css
      dest: /usr/share/nginx/html/switch.css
  - name: Setup ifacectl_client.js
    copy:
      src: ifacectl_client.js
      dest: /usr/share/nginx/html/ifacectl_client.js
  - name: Setup sopt_client.js
    copy:
      src: sopt_client.js
      dest: /usr/share/nginx/html/sopt_client.js
  - name: Setup window_scaling_client.js
    copy:
      src: window_scaling_client.js
      dest: /usr/share/nginx/html/window_scaling_client.js
  - name: Setup vsat.html
    template:
      src: vsat.html.j2
      dest: /usr/share/nginx/html/vsat.html
  - name: Start and enable nginx service
    service:
      name: nginx
      state: started
      enabled: yes

