ansible_host: localhost
ansible_connection: local

# These should match the interface names of the link to the vsat modem
# and west 128T, respectively
external_interface: eth2

# Details to connect to conductor
conductor_address: 192.168.2.100
conductor_username: admin
conductor_password: 128Tadmin

# Details of this 128T router and VSAT interface
west_router: west-128t
west_node: west-128t
west_interface: west-vsat

# Detauls of the 128T router on the other end
east_router: east-128t
east_node: east-128t
east_interface: east-vsat
